//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKPartsWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public string Id { get; set; }
        public string CityName { get; set; }
        public string ShortCode { get; set; }
        public string PhoneCode { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
