//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKPartsWebApi.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UKPartsDBEntities : DbContext
    {
        public UKPartsDBEntities()
            : base("name=UKPartsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EngineDetail> EngineDetails { get; set; }
        public virtual DbSet<FuelDetail> FuelDetails { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<AvailableFuelType> AvailableFuelTypes { get; set; }
        public virtual DbSet<AvailableModelYearInfo> AvailableModelYearInfoes { get; set; }
        public virtual DbSet<AvailablePart> AvailableParts { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ModelYear> ModelYears { get; set; }
        public virtual DbSet<AvailableModelEngine> AvailableModelEngines { get; set; }
        public virtual DbSet<PartRequestDetail> PartRequestDetails { get; set; }
    }
}
