//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKPartsWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public string Id { get; set; }
        public string ModelName { get; set; }
        public string BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
