//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKPartsWebApi.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRequestDetail
    {
        public string Id { get; set; }
        public string PartId { get; set; }
        public string ModelId { get; set; }
        public string ModelYearId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CityId { get; set; }
        public string EngineSizeId { get; set; }
        public string FuelId { get; set; }
        public string ColorId { get; set; }
        public string SelectedOption { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public string BrandId { get; set; }
        public string DeviceId { get; set; }
    }
}
